# metrics docs: https://docs.tendermint.com/master/nodes/metrics.html
groups:
  - name: fxcore-alerts
    rules:
      - alert: The fxCore node service
        expr: up{job="fxcore-node"} != 1
        for: 0m
        labels:
          level: critical
        annotations:
          description: "The fxCore node service not found"

      - alert: The fxCore consensus height
        expr: tendermint_consensus_height{job="fxcore-node"} - (tendermint_consensus_height{job="fxcore-node"} offset 1m) == 0
        for: 0m
        labels:
          level: critical
          monitor: tendermint_consensus_height
        annotations:
          description: "The fxCore node does not generate a block for 1 minute"

      - alert: The fxCore consensus validators
        expr: sum(tendermint_consensus_validators{job="fxcore-node"} - (tendermint_consensus_validators{job="fxcore-node"} offset 1m) != 0) by (job)
        for: 0m
        labels:
          level: critical
          monitor: tendermint_consensus_validators
        annotations:
          description: "The fxCore consensus validators has changed, current: {{$value}}"

      - alert: The fxCore node latest block height
        expr: tendermint_consensus_latest_block_height{job="fxcore-node"} - (tendermint_consensus_latest_block_height{job="fxcore-node"} offset 1m) == 0
        for: 0m
        labels:
          level: critical
          monitor: tendermint_consensus_latest_block_height
        annotations:
          description: "The fxCore node block height does not increase for 2 minutes"

      - alert: The fxCore node last signed height
        expr: tendermint_consensus_validator_last_signed_height{job="fxcore-node"} - (tendermint_consensus_validator_last_signed_height{job="fxcore-node"} offset 1m) == 0
        for: 0m
        labels:
          level: warning
          monitor: tendermint_consensus_validator_last_signed_height
        annotations:
          description: "The fxCore node did not participate in the block signing for 2 minutes"

      - alert: The fxCore node missed blocks
        expr: tendermint_consensus_validator_missed_blocks{job="fxcore-node"} - (tendermint_consensus_validator_missed_blocks{job="fxcore-node"} offset 1m) >= 3
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_validator_missed_blocks
        annotations:
          description: "The number of blocks not signed by the verifier exceeds the threshold of 100, current: {{$value}}"

      - alert: The fxCore node missing validators
        expr: tendermint_consensus_missing_validators{job="fxcore-node"} > 10
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_missing_validators
        annotations:
          description: "The fxCore node missing validators number exceeds the threshold 10, current: {{$value}}"

      - alert: The fxCore node byzantine validators
        expr: tendermint_consensus_byzantine_validators{job="fxcore-node"} > 0
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_byzantine_validators
        annotations:
          description: "The fxCore node byzantine validators number exceeds the threshold 0, current: {{$value}}"

      - alert: The fxCore node block interval seconds
        expr: tendermint_consensus_block_interval_seconds_sum{job="fxcore-node"} / tendermint_consensus_block_interval_seconds_count{job="fxcore-node"} > 7
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_block_interval_seconds_(sum/count)
        annotations:
          description: "The fxCore node block interval seconds, current: {{$value}}s"

      - alert: The fxCore node consensus rounds
        expr: tendermint_consensus_rounds{job="fxcore-node"} > 0
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_rounds
        annotations:
          description: "The fxCore node number of rounds > 0, current: {{$value}}s"

      - alert: The fxCore number of transactions
        expr: tendermint_consensus_num_txs{job="fxcore-node"} > 100
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_num_txs
        annotations:
          description: "The fxCore number of transactions > 100, current: {{$value}}"

      - alert: The fxCore node mempool number of uncommitted transactions
        expr: tendermint_mempool_size{job="fxcore-node"} > 100
        for: 1m
        labels:
          level: warning
          monitor: tendermint_mempool_size
        annotations:
          description: "The fxCore node number of uncommitted transactions > 100, current: {{$value}}"

      - alert: The fxCore mempool failed txs number
        expr: tendermint_mempool_failed_txs{job="fxcore-node"} - (tendermint_mempool_failed_txs{job="fxcore-node"} offset 1m) > 10
        for: 1m
        labels:
          level: warning
          monitor: tendermint_mempool_failed_txs
        annotations:
          description: "The fxCore failed transactions number in the memory pool has increased by more than 10 in 1 minute, current: {{$value}}"

      - alert: The fxCore node synchronization status
        expr: tendermint_consensus_fast_syncing{job="fxcore-node"} - (tendermint_consensus_fast_syncing{job="fxcore-node"} offset 1m) != 0
        for: 1m
        labels:
          level: warning
          monitor: tendermint_consensus_fast_syncing
        annotations:
          description: "The node synchronization status has changed, please check"

      - alert: The fxCore node p2p peers
        expr: tendermint_p2p_peers{job="fxcore-node"} < 5
        for: 1m
        labels:
          level: warning
          monitor: tendermint_p2p_peers
        annotations:
          description: "The fxCore node p2p peers is lower than 5, current: {{$value}}"
