name: Solhint

on:
  push:
    paths:
      - "solidity/contracts/**"
  pull_request:
    paths:
      - "solidity/contracts/**"

jobs:
  solhint:
    name: runner solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g solhint
      - run: solhint --version
      - run: cd solidity && solhint 'contracts/**/*.sol'
